In [2]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("giovamata/airlinedelaycauses")

# print("Path to dataset files:", path)

In [3]:
path = r"C:\Users\artkr\.cache\kagglehub\datasets\giovamata\airlinedelaycauses\versions\2"

In [4]:
import pandas as pd
import os

# Set path to your downloaded dataset folder
dataset_path =  path

# Load the CSV file
file_path = os.path.join(dataset_path, "DelayedFlights.csv")
df = pd.read_csv(file_path)

# Show some basic info
print(df.shape)

(1936758, 30)

In [5]:
df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,...,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,...,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,...,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,...,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,...,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [7]:
# Check for columns with null values
null_columns = df.columns[df.isnull().any()]
print("Columns with null values:", null_columns)

Columns with null values: Index(['ArrTime', 'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime',
       'ArrDelay', 'TaxiIn', 'TaxiOut', 'CarrierDelay', 'WeatherDelay',
       'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [8]:
df = df.drop('Unnamed: 0', axis=1)
col_names = ['Year','Month', 'Day Of Month','Day Of Week','Departure Time', 'Scheduled Departure Time','Arrival Time', 'Scheduled Arrival Time', 'Unique Carrier Code', 
             'Flight Number','Tail Number', 'Actual Elapsed Time','Estimated Elapsed Time','Air Time', 'Arrival Delay','Departure Delay','Origin', 'Destination',
             'Distance','Taxi In','Taxi Out', 'Cancelled', 'Cancellation Code','Diverted','Carrier Delay','Weather Delay', 'NAS Delay','Security Delay','Late Aircraft Delay']

# Fix column names, drop duplicates, show all columns
df.columns = col_names
df = df.drop_duplicates()
pd.set_option('display.max_columns', None)

df

,Year,Month,Day Of Month,Day Of Week,Departure Time,Scheduled Departure Time,Arrival Time,Scheduled Arrival Time,Unique Carrier Code,Flight Number,Tail Number,Actual Elapsed Time,Estimated Elapsed Time,Air Time,Arrival Delay,Departure Delay,Origin,Destination,Distance,Taxi In,Taxi Out,Cancelled,Cancellation Code,Diverted,Carrier Delay,Weather Delay,NAS Delay,Security Delay,Late Aircraft Delay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,128.0,150.0,116.0,-14.0,8.0,IAD,TPA,810,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,128.0,145.0,113.0,2.0,19.0,IAD,TPA,810,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,N428WN,96.0,90.0,76.0,14.0,8.0,IND,BWI,515,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,N726SW,101.0,115.0,87.0,11.0,25.0,IND,JAX,688,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,2008,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,2008,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,2008,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,2008,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,115.0,117.0,89.0,9.0,11.0,IAD,ATL,533,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,2008,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,123.0,135.0,104.0,-5.0,7.0,SAT,ATL,874,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.dtypes

Year                          int64
Month                         int64
Day Of Month                  int64
Day Of Week                   int64
Departure Time              float64
Scheduled Departure Time      int64
Arrival Time                float64
Scheduled Arrival Time        int64
Unique Carrier Code          object
Flight Number                 int64
Tail Number                  object
Actual Elapsed Time         float64
Estimated Elapsed Time      float64
Air Time                    float64
Arrival Delay               float64
Departure Delay             float64
Origin                       object
Destination                  object
Distance                      int64
Taxi In                     float64
Taxi Out                    float64
Cancelled                     int64
Cancellation Code            object
Diverted                      int64
Carrier Delay               float64
Weather Delay               float64
NAS Delay                   float64
Security Delay              float64
Late Aircraft Delay         float64
dtype: object

In [10]:
invalid_years = df[df['Year'] != 2008]
if not invalid_years.empty:
    print("Invalid Years:")
    print(invalid_years['Year'])

# Check month and print the rows where the month is not in the range 1-12
invalid_months = df[~df['Month'].between(1, 12)]
if not invalid_months.empty:
    print("Invalid Months:")
    print(invalid_months['Month'])

# Check day of the month and print the rows where the day is not in the range 1-31
invalid_month_day = df[~df['Day Of Month'].between(1, 31)]
if not invalid_month_day.empty:
    print("Invalid Month Day:")
    print(invalid_months['Day Of Month'])

# Check day of the week and print the rows where the day is not in the range 1-7
invalid_day = df[~df['Day Of Week'].between(1, 7)]
if not invalid_month_day.empty:
    print("Invalid Week Day:")
    print(invalid_months['Day Of Week'])

In [11]:
null_df_sums = df.isna().sum()
null_df_sums

Year                             0
Month                            0
Day Of Month                     0
Day Of Week                      0
Departure Time                   0
Scheduled Departure Time         0
Arrival Time                  7110
Scheduled Arrival Time           0
Unique Carrier Code              0
Flight Number                    0
Tail Number                      5
Actual Elapsed Time           8387
Estimated Elapsed Time         198
Air Time                      8387
Arrival Delay                 8387
Departure Delay                  0
Origin                           0
Destination                      0
Distance                         0
Taxi In                       7110
Taxi Out                       455
Cancelled                        0
Cancellation Code                0
Diverted                         0
Carrier Delay               689270
Weather Delay               689270
NAS Delay                   689270
Security Delay              689270
Late Aircraft Delay         689270
dtype: int64

In [12]:
'''
    There are 5 missing values for Tail Number, since these are needed to track the plane, 
    we can claim the data for that missing row is invalid
'''
df.dropna(subset=['Tail Number'], inplace=True)

In [13]:
''' 
Given:
    We already know the Cancelled and Cancellation Code columns are nonempty because the sum of their .isna()
    in the code cell above was equal to 0.

    If flight was cancelled (cancelled = 1), Taxi In, Taxi Out = 0.0
    
'''

cancelled_flights = df[df['Cancelled'] == 1]
cancelled_flight_codes = df[df['Cancellation Code'] != 'N']

print('There are',len(cancelled_flights), 'cancelled flights.')
print('There are',len(cancelled_flight_codes),'cancelled flight codes')

# Print the dataframe of the cancelled flight rows
cancelled_flights

There are 633 cancelled flights.
There are 633 cancelled flight codes

,Year,Month,Day Of Month,Day Of Week,Departure Time,Scheduled Departure Time,Arrival Time,Scheduled Arrival Time,Unique Carrier Code,Flight Number,Tail Number,Actual Elapsed Time,Estimated Elapsed Time,Air Time,Arrival Delay,Departure Delay,Origin,Destination,Distance,Taxi In,Taxi Out,Cancelled,Cancellation Code,Diverted,Carrier Delay,Weather Delay,NAS Delay,Security Delay,Late Aircraft Delay
1542406,2008,10,27,1,1622.0,1420,NaN,1520,WN,27,N601WN,NaN,60.0,NaN,NaN,122.0,HOU,HRL,276,NaN,19.0,1,A,0,NaN,NaN,NaN,NaN,NaN
1546593,2008,10,25,6,1323.0,1255,NaN,1442,XE,2347,N26549,NaN,107.0,NaN,NaN,28.0,CLT,EWR,529,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
1547161,2008,10,22,3,1825.0,1815,NaN,1927,XE,2819,N12946,NaN,72.0,NaN,NaN,10.0,JAN,IAH,351,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
1547178,2008,10,22,3,1733.0,1715,NaN,1818,XE,2890,N16944,NaN,63.0,NaN,NaN,18.0,IAH,BTR,253,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
1548271,2008,10,15,3,1943.0,1745,NaN,1857,XE,2117,N26545,NaN,72.0,NaN,NaN,118.0,IAH,HRL,295,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1934590,2008,12,7,7,1526.0,1444,NaN,1654,DL,1743,N958DL,NaN,130.0,NaN,NaN,42.0,BUF,ATL,712,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1935491,2008,12,10,3,1431.0,1422,NaN,1527,DL,1405,N906DL,NaN,125.0,NaN,NaN,9.0,ATL,IAH,689,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
1935651,2008,12,10,3,1459.0,1447,NaN,1650,DL,1706,N914DN,NaN,123.0,NaN,NaN,12.0,ATL,BUF,712,NaN,37.0,1,A,0,NaN,NaN,NaN,NaN,NaN
1935876,2008,12,11,4,1026.0,955,NaN,1219,DL,892,N928DL,NaN,144.0,NaN,NaN,31.0,ATL,JFK,760,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1936470,2008,12,12,5,703.0,630,NaN,734,DL,1372,N908DE,NaN,64.0,NaN,NaN,33.0,LGA,BOS,185,NaN,33.0,1,B,0,NaN,NaN,NaN,NaN,NaN

In [14]:
'''
    We see that all cancelled flights have NaN for Taxi in, actual elapsed time, and NaN for all delay codes
    Let's and write "0.0" for arrival time, actual elapsed time, air time, arrival delay, taxi in, and taxi out
    for NaN values in cancelled flights.
'''
df['Arrival Time'] = df['Arrival Time'].fillna(value=0.0)
df['Actual Elapsed Time'] = df['Actual Elapsed Time'].fillna(value=0.0)
df['Air Time'] = df['Air Time'].fillna(value=0.0)
df['Arrival Delay'] = df['Arrival Delay'].fillna(value=0.0)
df['Taxi In'] = df['Taxi In'].fillna(value=0.0)
df['Taxi Out'] = df['Taxi Out'].fillna(value=0.0)

In [15]:
cause_cols = ["Carrier Delay", "Weather Delay", "NAS Delay", "Security Delay", "Late Aircraft Delay"]

df = df.drop(columns=cause_cols)

print("Dataset shape after dropping rows with NaN delay causes:", df.shape)

Dataset shape after dropping rows with NaN delay causes: (1936751, 24)

In [16]:
# Check for columns with null values
null_columns = df.columns[df.isnull().any()]
print("Columns with null values:", null_columns)

Columns with null values: Index(['Estimated Elapsed Time'], dtype='object')

In [17]:
# Drop rows where flight was cancelled
df = df[df["Cancelled"] != 1]
# Drop the specified columns
columns_to_drop = [
    'Scheduled Departure Time', 'Arrival Time', 'Scheduled Arrival Time', 
    'Unique Carrier Code', 'Flight Number', 'Tail Number', 
    'Actual Elapsed Time', 'Estimated Elapsed Time', 
    'Origin', 'Destination', 'Taxi In', 'Taxi Out', 
    'Cancelled', 'Cancellation Code'
]

df = df.drop(columns=columns_to_drop)

print("Data shape after dropping cancelled rows and columns:", df.shape)

Data shape after dropping cancelled rows and columns: (1936118, 10)

In [18]:
df

,Year,Month,Day Of Month,Day Of Week,Departure Time,Air Time,Arrival Delay,Departure Delay,Distance,Diverted
0,2008,1,3,4,2003.0,116.0,-14.0,8.0,810,0
1,2008,1,3,4,754.0,113.0,2.0,19.0,810,0
2,2008,1,3,4,628.0,76.0,14.0,8.0,515,0
3,2008,1,3,4,1829.0,77.0,34.0,34.0,515,0
4,2008,1,3,4,1940.0,87.0,11.0,25.0,688,0
...,...,...,...,...,...,...,...,...,...,...
1936753,2008,12,13,6,1250.0,120.0,25.0,30.0,906,0
1936754,2008,12,13,6,657.0,78.0,75.0,57.0,481,0
1936755,2008,12,13,6,1007.0,122.0,99.0,80.0,689,0
1936756,2008,12,13,6,1251.0,89.0,9.0,11.0,533,0
1936757,2008,12,13,6,1110.0,104.0,-5.0,7.0,874,0

In [19]:
# Save the cleaned dataset to CSV
df.to_csv("cleaned_delayed_flights.csv", index=False)

print("✅ Cleaned dataset saved as cleaned_delayed_flights.csv")

✅ Cleaned dataset saved as cleaned_delayed_flights.csv